### ISSUE TITLE
Emotes are not included in chat logs

### ISSUE THREAD

**Issue by Xslare** [WaywardRealms/Wayward#293]
Probably should fix that, or at least use a composite log if merging isn't possible.

**Comment by alyphen** [comment]
Emotes are currently included in the chat log for the default channel.

**Comment by alyphen** [comment]
This is definitely logged [here](https://github.com/WaywardRealms/Wayward/blob/master/WaywardChat/src/main/java/net/wayward_realms/waywardchat/AsyncPlayerChatListener.java#L67)
